#!/usr/bin/env python3
"""Generate L10n artifacts from the single source of truth Resources/l10n/en.json.

Emits:
1. Resources/l10n/en.lproj/Localizable.strings
   - Key = the Chinese literal as SwiftUI builds it at runtime:
     \\(Int-expr) -> %lld, \\(other) -> %@ ; keys containing a literal '%'
     are emitted twice (raw and %%-escaped) as lookup insurance.
2. Sources/OPCCompanyCore/AppStringsGenerated.swift
   - zh -> en reverse map for dynamic strings (enum titles, store markers).
"""
import json, os, re

ROOT = os.path.expanduser("~/Desktop/OPCCompany")
SRC = os.path.join(ROOT, "Resources/l10n/en.json")

data = json.load(open(SRC, encoding="utf-8"))
mapping = data["map"]

INT_KEY = re.compile(r"\\\(count\b|\\\(.*?\.count\)|\\\(.*?[\+\-\*/].*?\)")

def swiftui_key(zh: str) -> str:
    """Convert a source literal into the runtime LocalizedStringKey form."""
    def repl(m):
        expr = m.group(1)
        if re.search(r"\.count$|\.count\)|^count$|Count\b|^\w+$", expr) and not re.search(r"\.title|\.name|displayName|summary|reason|goal|Path|Text\(", expr):
            return "%lld"
        return "%@"
    return re.sub(r"\\\(([^)]*)\)", repl, zh)

def strings_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")

def swift_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")

# ---- 1. Localizable.strings ----
entries = {}
for zh, en in mapping.items():
    key = swiftui_key(zh)
    entries[key] = en
    if "%" in key.replace("%lld", "").replace("%@", ""):
        # literal % ambiguity: add %% variant as fallback key
        entries[key.replace("%", "%%")] = en

lines = ["/* Generated by scripts/generate_l10n.py — DO NOT EDIT BY HAND.",
         "   Source of truth: Resources/l10n/en.json */", ""]
for k in sorted(entries):
    lines.append(f'"{strings_escape(k)}" = "{strings_escape(entries[k])}";')
out_strings = os.path.join(ROOT, "Resources/l10n/en.lproj/Localizable.strings")
os.makedirs(os.path.dirname(out_strings), exist_ok=True)
open(out_strings, "w", encoding="utf-8").write("\n".join(lines) + "\n")

# ---- 1b. zh-Hans identity table ----
# The Chinese source strings ARE the keys. Without a zh-Hans table, a zh-Hans
# locale request falls back to en.lproj and returns English. Identity mapping
# makes zh lookups always hit with the original Chinese copy.
zh_lines = ["/* Generated by scripts/generate_l10n.py — DO NOT EDIT BY HAND.",
            "   Identity table: zh-Hans keys resolve to the original Chinese copy. */", ""]
for k in sorted(entries):
    zh_lines.append(f'"{strings_escape(k)}" = "{strings_escape(k)}";')
out_zh = os.path.join(ROOT, "Resources/l10n/zh-Hans.lproj/Localizable.strings")
os.makedirs(os.path.dirname(out_zh), exist_ok=True)
open(out_zh, "w", encoding="utf-8").write("\n".join(zh_lines) + "\n")

# ---- 2. Swift reverse map ----
swift = ['// Generated by scripts/generate_l10n.py — DO NOT EDIT BY HAND.',
         '// Source of truth: Resources/l10n/en.json',
         'import Foundation',
         '',
         'enum AppStringsGenerated {',
         '    static let zhToEn: [String: String] = [']
for zh in sorted(mapping):
    swift.append(f'        "{swift_escape(zh)}": "{swift_escape(mapping[zh])}",')
swift.append('    ]')
swift.append('}')
out_swift = os.path.join(ROOT, "Sources/OPCCompanyCore/AppStringsGenerated.swift")
open(out_swift, "w", encoding="utf-8").write("\n".join(swift) + "\n")

print("strings entries:", len(entries), "->", os.path.relpath(out_strings, ROOT))
print("swift reverse map:", len(mapping), "->", os.path.relpath(out_swift, ROOT))
